# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.example.com:
    container_name: orderer.example.com
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/:/var/hyperledger/orderer/tls
    ports:
      - 7050:7050

  peer0.assetManagerOrg.example.com:
    container_name: peer0.assetManagerOrg.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.assetManagerOrg.example.com
      - CORE_PEER_ADDRESS=peer0.assetManagerOrg.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.assetManagerOrg.example.com:7051
      - CORE_PEER_LOCALMSPID=AssetManagerOrgMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/assetManagerOrg.example.com/peers/peer0.assetManagerOrg.example.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/assetManagerOrg.example.com/peers/peer0.assetManagerOrg.example.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7051:7051
      - 7053:7053

  peer1.assetManagerOrg.example.com:
    container_name: peer1.assetManagerOrg.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.assetManagerOrg.example.com
      - CORE_PEER_ADDRESS=peer1.assetManagerOrg.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.assetManagerOrg.example.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.assetManagerOrg.example.com:7051
      - CORE_PEER_LOCALMSPID=AssetManagerOrgMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/assetManagerOrg.example.com/peers/peer1.assetManagerOrg.example.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/assetManagerOrg.example.com/peers/peer1.assetManagerOrg.example.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 8051:7051
      - 8053:7053

  peer0.assetCollectorOrg.example.com:
    container_name: peer0.assetCollectorOrg.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.assetCollectorOrg.example.com
      - CORE_PEER_ADDRESS=peer0.assetCollectorOrg.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.assetCollectorOrg.example.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.assetCollectorOrg.example.com:7051
      - CORE_PEER_LOCALMSPID=AssetCollectorOrgMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/assetCollectorOrg.example.com/peers/peer0.assetCollectorOrg.example.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/assetCollectorOrg.example.com/peers/peer0.assetCollectorOrg.example.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 9051:7051
      - 9053:7053

  peer1.assetCollectorOrg.example.com:
    container_name: peer1.assetCollectorOrg.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.assetCollectorOrg.example.com
      - CORE_PEER_ADDRESS=peer1.assetCollectorOrg.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.assetCollectorOrg.example.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.assetCollectorOrg.example.com:7051
      - CORE_PEER_LOCALMSPID=AssetCollectorOrgMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/assetCollectorOrg.example.com/peers/peer1.assetCollectorOrg.example.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/assetCollectorOrg.example.com/peers/peer1.assetCollectorOrg.example.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 10051:7051
      - 10053:7053

  peer0.assetProviderOrg.example.com:
    container_name: peer0.assetProviderOrg.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.assetProviderOrg.example.com
      - CORE_PEER_ADDRESS=peer0.assetProviderOrg.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.assetProviderOrg.example.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.assetProviderOrg.example.com:7051
      - CORE_PEER_LOCALMSPID=AssetProviderOrgMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/assetProviderOrg.example.com/peers/peer0.assetProviderOrg.example.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/assetProviderOrg.example.com/peers/peer0.assetProviderOrg.example.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 11051:7051
      - 11053:7053

  peer1.assetProviderOrg.example.com:
    container_name: peer1.assetProviderOrg.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.assetProviderOrg.example.com
      - CORE_PEER_ADDRESS=peer1.assetProviderOrg.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.assetProviderOrg.example.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.assetProviderOrg.example.com:7051
      - CORE_PEER_LOCALMSPID=AssetProviderOrgMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/assetProviderOrg.example.com/peers/peer1.assetProviderOrg.example.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/assetProviderOrg.example.com/peers/peer1.assetProviderOrg.example.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 12051:7051
      - 12053:7053